### ISSUE TITLE
Suggest api doesn't work 

### ISSUE THREAD

**Issue by Ghassanee** [ravpacheco/check-name#2]
I'm trying to use your API with french names but I can't suggest new names.

**Comment by ravpacheco** [comment]
Hi @Ghassanee, 

thanks for your interest to contribute with check-name.
I'm a little bit busy for the next 2 weeks but I will try to enable suggestions endpoint as soon as possible.

Please, feel free to make a PR to accelerate the French language support.

I hope to see you here helping the project.
See you!
